### ISSUE TITLE
Hive Server - Error: Requested start date is not supported by any possible table.

### ISSUE THREAD

**Issue by Dan6erbond** [graphql-hive/platform#5034]
I'm running Hive on Kubernetes. Starting the latest version of the app results in the following error in the `graphql-hive/server` container.

```
Error: Requested start date is not supported by any possible table.
    at pickTableByPeriod (file:///usr/src/app/@hive/server/index.js:303050:11)
    at OperationsReader.pickAggregationByPeriod (file:///usr/src/app/@hive/server/index.js:303726:27)
    at OperationsReader.requestsOverTimeOfTargets (file:///usr/src/app/@hive/server/index.js:304698:64)
    at OperationsManager.requestsOverTimeOfTargetsLoader.import_dataloader5.default.cacheKeyFn [as _batchLoadFn] (file:///usr/src/app/@hive/server/index.js:325126:41)
    at dispatchBatch (file:///usr/src/app/@hive/server/index.js:62995:31)
    at Timeout._onTimeout (file:///usr/src/app/@hive/server/index.js:62982:9)
    at listOnTimeout (node:internal/timers:573:17)
    at process.processTimers (node:internal/timers:514:7) {
  locations: [ { line: 21, column: 7 } ],
  path: [ 'projects', 'nodes', 1, 'requestsOverTime' ]
}
```

**Comment by andriihrachov** [comment]
same

**Comment by n1ru4l** [comment]
@andriihrachov @Dan6erbond  Can you help us by sharing what views and which parameters cause this? https://github.com/kamilkisiela/graphql-hive/blob/3a45ffc4dee2f85a790ab811019a13a643b666d5/packages/services/api/src/modules/operations/lib/pick-table-by-provider.ts#L39

https://github.com/kamilkisiela/graphql-hive/blob/3a45ffc4dee2f85a790ab811019a13a643b666d5/packages/services/api/src/modules/operations/lib/pick-table-by-provider.ts#L45-L50

**Comment by andriihrachov** [comment]
In our case, self-healed with updating hive again. We also experienced problems with clickhouse connectivity, maybe it was the root cause, e.g. error is not correct in this case.

Once we updated hive & fixed connectivity issues - no errors so far.
