### ISSUE TITLE
Remote Docker not working

### ISSUE THREAD

**Issue by emedina** [graphql-hive/platform#5876]
I'm trying to run GraphQL Hive using the docker-compose provided.

Due to the fact that I'm using a remote Docker through TCP port, I'm changing all the localhost references in the `docker-compose.yaml` file to the name of my server, in this case `luu3198d`.

But then, when I try to start everything up, `hive-server-1` fails with an error that I don't know how to handle:

```
hive-server-1                | {"level":20,"time":1731068288862,"pid":7,"hostname":"96d833f676d2","msg":"Creating worker 0"}
hive-server-1                | {"level":20,"time":1731068288864,"pid":7,"hostname":"96d833f676d2","msg":"Creating worker 1"}
hive-server-1                | {"level":20,"time":1731068288865,"pid":7,"hostname":"96d833f676d2","msg":"Creating worker 2"}
hive-server-1                | {"level":20,"time":1731068288865,"pid":7,"hostname":"96d833f676d2","msg":"Creating worker 3"}
hive-server-1                | {"level":30,"time":1731068288999,"pid":7,"hostname":"96d833f676d2","msg":"SuperTokens providers: oidc"}
hive-server-1                | {"level":30,"time":1731068288999,"pid":7,"hostname":"96d833f676d2","msg":"SuperTokens websiteDomain: http://luu3198d:8080"}
hive-server-1                | {"level":30,"time":1731068288999,"pid":7,"hostname":"96d833f676d2","msg":"SuperTokens apiDomain: http://luu3198d:8082"}
hive-server-1                | {"level":60,"time":1731068289039,"pid":7,"hostname":"96d833f676d2","err":{"type":"Error","message":"Please make sure that the apiDomain and websiteDomain have correct values","stack":"Error: Please make sure that the apiDomain and websiteDomain have correct values\n    at getTopLevelDomainForSameSiteResolution (file:///usr/src/app/@hive/server/index.js:35908:15)\n    at Object.normaliseInputAppInfoOrThrowError (file:///usr/src/app/@hive/server/index.js:35804:33)\n    at new SuperTokens (file:///usr/src/app/@hive/server/index.js:52156:32)\n    at Object.init (file:///usr/src/app/@hive/server/index.js:52187:35)\n    at initSupertokens (file:///usr/src/app/@hive/server/index.js:353846:35)\n    at main (file:///usr/src/app/@hive/server/index.js:354219:5)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)"},"msg":"Please make sure that the apiDomain and websiteDomain have correct values"}
hive-server-1 exited with code 1
```

**Comment by n1ru4l** [comment]
This error is thrown from this call here: https://github.com/graphql-hive/platform/blob/49941b69aedc2229ea01d78c09255a9be6f339c1/packages/services/server/src/supertokens.ts#L366 and originates from the following values: https://github.com/graphql-hive/platform/blob/49941b69aedc2229ea01d78c09255a9be6f339c1/packages/services/server/src/supertokens.ts#L113-L114

Which can be traced back to the environment variables `GRAPHQL_PUBLIC_ORIGIN` and `WEB_APP_URL`. Can you share with us what values you use for these values?

**Comment by emedina** [comment]
`GRAPHQL_PUBLIC_ORIGIN: http://luu3198d:8082`

`WEB_APP_URL: '${HIVE_APP_BASE_URL}'`

`export HIVE_APP_BASE_URL="http://luu3198d:8080"`

So ports are different, but this is coming from the original code, not something I had to adapt when replacing "localhost" for "luu3198d".

**Comment by n1ru4l** [comment]
It seems like this issue is very similar to https://github.com/graphql-hive/platform/issues/4981 and https://github.com/supertokens/supertokens-node/issues/823

We are currently behind a few versions of the Supertokens SDK. This issue may have already been resolved in a newer version of the supertokens-node SDK.

A current workaround would be to use a TLD.

**Comment by n1ru4l** [comment]
We are no longer using supertokens-node.
